# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - sync-api

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://syncregistry.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_4d10f329f44341eb85f28149a458e43f }}
        password: ${{ secrets.AzureAppService_ContainerPassword_46082ae97ed745d8b215d6b5ff6debc5 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: syncregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_4d10f329f44341eb85f28149a458e43f }}/sync-api:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'sync-api'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_b17631f068024c6f934914d4d7bfbc36 }}
        images: 'syncregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_4d10f329f44341eb85f28149a458e43f }}/sync-api:${{ github.sha }}'